-----------------------------------------------------------------------------------------------------------------------------------------
-- NEARVEHICLE
-----------------------------------------------------------------------------------------------------------------------------------------
function nearVehicle(radius)
    local vehList = {}
    local vehReturn = {}
    local ped = PlayerPedId()
    local coords = GetEntityCoords(ped)

    local _next, _vehicle = FindFirstVehicle()
    if _vehicle then table.insert(vehList, _vehicle) end

    repeat
        local _nextVehicle, _vehicle = FindNextVehicle(_next)
        if _nextVehicle and _vehicle then table.insert(vehList, _vehicle) end
    until not _nextVehicle

    EndFindVehicle(_next)

    for k, v in pairs(vehList) do
        local uCoords = GetEntityCoords(v)
        local distance = #(coords - uCoords)
        if distance <= radius then vehReturn[v] = distance end
    end

    return vehReturn
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- NEARVEHICLE
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.nearVehicle(radius)
    local vehSelect = false
    local minRadius = radius + 0.0001
    local vehList = nearVehicle(radius)

    for _vehicle, _distance in pairs(vehList) do
        if _distance <= minRadius then
            minRadius = _distance
            vehSelect = _vehicle
        end
    end

    return vehSelect
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- INVEHICLE
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.inVehicle()
    local ped = PlayerPedId()
    return IsPedInAnyVehicle(ped)
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
local vehList = {
    {"g7cross", false},
	{"golfrebaixado", false},
	{"pcx", false},
    {"trailblazer", false},
	{"porscheag", false},
	{"jeepag", false},
    {"dinghy", true},
	{"dinghy2", false},
	{"dinghy3", false},
    {"dinghy4", false},
	{"jetmax", true},
	{"marquis", true},
	{"seashark", true},
    {"seashark2", false},
	{"seashark3", false},
	{"speeder", true},
    {"speeder2", false},
	{"squalo", true},
	{"submersible", false},
    {"submersible2", false},
	{"suntrap", true},
	{"toro", true},
    {"toro2", false},
	{"tropic", true},
	{"tropic2", false},
	{"tug", false},
    {"benson", false},
	{"biff", false},
	{"cerberus", false},
    {"cerberus2", false},
	{"cerberus3", false},
	{"hauler", false},
    {"hauler2", false},
	{"mule", false},
	{"mule2", false},
	{"mule3", false},
    {"mule4", false},
	{"packer", true},
	{"phantom", false},
	{"phantom2", false},
    {"phantom3", false},
	{"pounder", false},
	{"pounder2", false},
    {"stockade", false},
	{"stockade2", true},
	{"stockade3", false},
    {"terbyte", false},
	{"blista", false},
	{"brioso", false},
    {"dilettante", false},
	{"dilettante2", false},
	{"issi2", false},
    {"issi3", false},
	{"issi4", false},
	{"issi5", false},
	{"issi6", false},
    {"panto", false},
	{"prairie", false},
	{"rhapsody", false},
    {"cogcabrio", false},
	{"exemplar", false},
	{"f620", false},
    {"felon", false},
	{"felon2", false},
	{"jackal", false},
	{"oracle", false},
    {"oracle2", false},
	{"sentinel", false},
	{"sentinel2", false},
    {"windsor", false},
	{"windsor2", false},
	{"zion", false},
	{"zion2", false},
    {"bmx", true},
	{"cruiser", true},
	{"fixter", true},
	{"scorcher", true},
    {"tribike", true},
	{"tribike2", true},
	{"tribike3", true},
    {"ambulance", false},
	{"fbi", true},
	{"fbi2", true},
	{"firetruk", true},
    {"lguard", true},
	{"pbus", true},
	{"police", true},
	{"police2", true},
    {"police3", true},
	{"police4", false},
	{"policeb", true},
	{"polmav", true},
    {"policeold1", true},
	{"policeold2", true},
	{"policet", true},
    {"pranger", true},
	{"predator", true},
	{"riot", true},
	{"riot2", true},
    {"sheriff", true},
	{"sheriff2", true},
	{"akula", false},
    {"annihilator", false},
	{"buzzard", false},
	{"buzzard2", true},
    {"cargobob", false},
	{"cargobob2", false},
	{"cargobob3", false},
    {"cargobob4", false},
	{"frogger", true},
	{"frogger2", false},
    {"havok", true},
	{"hunter", false},
	{"maverick", true},
	{"maverick2", true},
    {"savage", false},
	{"seasparrow", false},
	{"skylift", false},
    {"supervolito", true},
	{"supervolito2", false},
	{"swift", true},
    {"swift2", true},
	{"valkyrie", false},
	{"valkyrie2", false},
    {"volatus", true},
	{"bulldozer", false},
	{"cutter", false},
	{"dump", false},
    {"flatbed", true},
	{"guardian", false},
	{"handler", false},
    {"mixer", false},
	{"mixer2", false},
	{"rubble", false},
	{"tiptruck", false},
    {"tiptruck2", false},
	{"apc", false},
	{"barracks", false},
    {"barracks2", false},
	{"barracks3", false},
	{"barrage", false},
    {"chernobog", false},
	{"crusader", false},
	{"halftrack", false},
    {"khanjali", false},
	{"rhino", false},
	{"scarab", false},
    {"scarab2", false},
	{"scarab3", false},
	{"thruster", false},
    {"trailersmall2", false},
	{"akuma", false},
	{"avarus", false},
    {"bagger", false},
	{"bati", false},
	{"bati2", false},
	{"bf400", false},
    {"carbonrs", false},
	{"chimera", false},
	{"cliffhanger", false},
    {"daemon", false},
	{"daemon2", false},
	{"defiler", false},
    {"deathbike", false},
	{"deathbike2", false},
	{"deathbike3", false},
    {"diablous", false},
	{"diablous2", false},
	{"double", false},
    {"enduro", false},
	{"esskey", false},
	{"faggio", true},
	{"faggio2", false},
    {"faggio3", false},
	{"fcr", false},
	{"fcr2", false},
	{"gargoyle", false},
    {"hakuchou", false},
	{"hakuchou2", false},
	{"hexer", false},
    {"innovation", false},
	{"lectro", false},
	{"manchez", false},
    {"nemesis", false},
	{"nightblade", false},
	{"oppressor", false},
    {"oppressor2", false},
	{"pcj", false},
	{"ratbike", false},
    {"ruffian", false},
	{"sanchez", false},
	{"sanchez2", false},
    {"sanctus", false},
	{"shotaro", false},
	{"sovereign", false},
    {"thrust", false},
	{"vader", false},
	{"vindicator", false},
    {"vortex", false},
	{"wolfsbane", false},
	{"zombiea", false},
    {"zombieb", false},
	{"blade", false},
	{"buccaneer", false},
    {"buccaneer2", false},
	{"chino", false},
	{"chino2", false},
    {"clique", false},
	{"coquette3", false},
	{"deviant", false},
    {"dominator", false},
	{"dominator2", false},
	{"dominator3", false},
    {"dominator4", false},
	{"dominator5", false},
	{"dominator6", false},
    {"dukes", false},
	{"dukes2", false},
	{"faction", false},
    {"faction2", false},
	{"faction3", false},
	{"ellie", false},
    {"gauntlet", false},
	{"gauntlet2", false},
	{"hermes", false},
    {"hotknife", false},
	{"hustler", false},
	{"impaler", false},
    {"impaler2", false},
	{"impaler3", false},
	{"impaler4", false},
    {"imperator", false},
	{"imperator2", false},
	{"imperator3", false},
    {"lurcher", false},
	{"moonbeam", false},
	{"moonbeam2", false},
    {"nightshade", false},
	{"phoenix", false},
	{"picador", false},
    {"ratloader", false},
	{"ratloader2", false},
	{"ruiner", false},
    {"ruiner2", false},
	{"ruiner3", false},
	{"sabregt", false},
    {"sabregt2", false},
	{"slamvan", false},
	{"slamvan2", false},
    {"slamvan3", false},
	{"slamvan4", false},
	{"slamvan5", false},
    {"slamvan6", false},
	{"stalion", false},
	{"stalion2", false},
    {"tampa", false},
	{"tampa3", false},
	{"tulip", false},
	{"vamos", false},
    {"vigero", false},
	{"virgo", false},
	{"virgo2", false},
	{"virgo3", false},
    {"voodoo", false},
	{"voodoo2", false},
	{"yosemite", false},
    {"bfinjection", false},
	{"bifta", false},
	{"blazer", false},
    {"blazer2", true},
	{"blazer3", false},
	{"blazer4", false},
    {"blazer5", false},
	{"bodhi2", false},
	{"brawler", false},
    {"bruiser", false},
	{"bruiser2", false},
	{"bruiser3", false},
    {"brutus", false},
	{"brutus2", false},
	{"brutus3", false},
    {"caracara", false},
	{"dloader", false},
	{"dubsta3", false},
    {"dune", false},
	{"dune2", false},
	{"dune3", false},
	{"dune4", false},
    {"dune5", false},
	{"freecrawler", false},
	{"insurgent", false},
    {"insurgent2", false},
	{"insurgent3", false},
	{"kalahari", false},
    {"kamacho", false},
	{"marshall", false},
	{"mesa3", false},
    {"monster", false},
	{"monster3", false},
	{"monster4", false},
    {"monster5", false},
	{"menacer", false},
	{"nightshark", false},
    {"rancherxl", false},
	{"rancherxl2", false},
	{"rebel", false},
    {"rebel2", false},
	{"rcbandito", false},
	{"riata", false},
    {"sandking", false},
	{"sandking2", false},
	{"technical", false},
    {"technical2", false},
	{"technical3", false},
	{"trophytruck", false},
    {"trophytruck2", false},
	{"alphaz1", false},
	{"avenger", false},
    {"avenger2", false},
	{"besra", false},
	{"blimp", false},
	{"blimp2", false},
    {"blimp3", false},
	{"bombushka", false},
	{"cargoplane", false},
    {"cuban800", true},
	{"dodo", true},
	{"duster", false},
	{"howard", false},
    {"hydra", false},
	{"jet", false},
	{"lazer", false},
	{"luxor", true},
    {"luxor2", false},
	{"mammatus", true},
	{"microlight", false},
    {"miljet", true},
	{"mogul", false},
	{"molotok", false},
	{"nimbus", true},
    {"nokota", false},
	{"pyro", false},
	{"rogue", false},
	{"seabreeze", false},
    {"shamal", true},
	{"starling", false},
	{"strikeforce", false},
    {"stunt", false},
	{"titan", false},
	{"tula", false},
	{"velum", true},
    {"velum2", false},
	{"vestra", false},
	{"volatol", false},
	{"baller", false},
    {"baller2", false},
	{"baller3", false},
	{"baller4", false},
    {"baller5", false},
	{"baller6", false},
	{"bjxl", false},
    {"cavalcade", false},
	{"cavalcade2", false},
	{"contender", false},
    {"dubsta", false},
	{"dubsta2", false},
	{"fq2", false},
	{"granger", false},
    {"gresley", false},
	{"habanero", false},
	{"huntley", false},
    {"landstalker", false},
	{"mesa", false},
	{"mesa2", false},
    {"patriot", false},
	{"patriot2", false},
	{"radi", false},
	{"rocoto", false},
    {"seminole", false},
	{"serrano", false},
	{"toros", false},
	{"xls", false},
    {"xls2", false},
	{"asea", false},
	{"asea2", false},
	{"asterope", false},
    {"cog55", false},
	{"cog552", false},
	{"cognoscenti", false},
    {"cognoscenti2", false},
	{"emperor", false},
	{"emperor2", false},
    {"emperor3", false},
	{"fugitive", false},
	{"glendale", false},
    {"ingot", false},
	{"intruder", false},
	{"limo2", false},
	{"premier", false},
    {"primo", false},
	{"primo2", false},
	{"regina", false},
	{"romero", false},
    {"schafter2", false},
	{"schafter5", false},
	{"schafter6", false},
    {"stafford", false},
	{"stanier", false},
	{"stratum", false},
    {"stretch", false},
	{"superd", false},
	{"surge", false},
    {"tailgater", false},
	{"warrener", false},
	{"washington", false},
    {"airbus", false},
	{"brickade", false},
	{"bus", true},
	{"coach", false},
    {"pbus2", false},
	{"rallytruck", false},
	{"rentalbus", false},
    {"taxi", true},
	{"tourbus", false},
	{"trash", false},
	{"trash2", false},
    {"wastelander", false},
	{"alpha", false},
	{"banshee", false},
    {"bestiagts", false},
	{"blista2", false},
	{"blista3", false},
    {"buffalo", false},
	{"buffalo2", false},
	{"buffalo3", false},
    {"carbonizzare", false},
	{"comet2", false},
	{"comet3", false},
    {"comet4", false},
	{"comet5", false},
	{"coquette", false},
    {"deveste", false},
	{"elegy", false},
	{"elegy2", false},
    {"feltzer2", false},
	{"flashgt", false},
	{"furoregt", false},
    {"fusilade", false},
	{"futo", false},
	{"gb200", false},
	{"hotring", false},
    {"italigto", false},
	{"jester", false},
	{"jester2", false},
    {"jester3", false},
	{"khamelion", false},
	{"kuruma", false},
    {"kuruma2", false},
	{"lynx", false},
	{"massacro", false},
    {"massacro2", false},
	{"neon", false},
	{"ninef", false},
	{"ninef2", false},
    {"omnis", false},
	{"pariah", false},
	{"penumbra", false},
	{"raiden", false},
    {"rapidgt", false},
	{"rapidgt2", false},
	{"raptor", false},
    {"revolter", false},
	{"ruston", false},
	{"schafter3", false},
    {"schafter4", false},
	{"schafter5", false},
	{"schafter6", false},
    {"schlagen", false},
	{"schwarzer", false},
	{"sentinel3", false},
    {"seven70", false},
	{"specter", false},
	{"specter2", false},
    {"streiter", false},
	{"sultan", false},
	{"surano", false},
    {"tampa2", false},
	{"tropos", false},
	{"verlierer2", false},
    {"zr380", false},
	{"zr3802", false},
	{"zr3803", false},
	{"ardent", false},
    {"btype", false},
	{"btype2", false},
	{"btype3", false},
	{"casco", false},
    {"cheetah2", false},
	{"coquette2", false},
	{"deluxo", false},
    {"fagaloa", false},
	{"feltzer3", false},
	{"gt500", false},
    {"infernus2", false},
	{"jb700", false},
	{"mamba", false},
	{"manana", false},
    {"michelli", false},
	{"monroe", false},
	{"peyote", false},
    {"pigalle", false},
	{"rapidgt3", false},
	{"retinue", false},
    {"savestra", false},
	{"stinger", false},
	{"stingergt", false},
    {"stromberg", false},
	{"swinger", false},
	{"torero", false},
    {"tornado", false},
	{"tornado2", false},
	{"tornado3", false},
    {"tornado4", false},
	{"tornado5", false},
	{"tornado6", false},
    {"turismo2", false},
	{"viseris", false},
	{"z190", false},
	{"ztype", false},
    {"cheburek", false},
	{"adder", false},
	{"autarch", false},
    {"banshee2", false},
	{"bullet", false},
	{"cheetah", false},
    {"cyclone", false},
	{"entity2", false},
	{"entityxf", false},
	{"fmj", false},
    {"gp1", false},
	{"infernus", false},
	{"italigtb", false},
    {"italigtb2", false},
	{"le7b", false},
	{"nero", false},
	{"nero2", false},
    {"osiris", false},
	{"penetrator", false},
	{"pfister811", false},
    {"prototipo", false},
	{"reaper", false},
	{"sc1", false},
    {"scramjet", false},
	{"sheava", false},
	{"sultanrs", false},
	{"t20", false},
    {"taipan", false},
	{"tempesta", false},
	{"tezeract", false},
    {"turismor", false},
	{"tyrant", false},
	{"tyrus", false},
	{"vacca", false},
    {"vagner", false},
	{"vigilante", false},
	{"visione", false},
    {"voltic", false},
	{"voltic2", false},
	{"xa21", false},
	{"zentorno", false},
    {"armytanker", true},
	{"armytrailer", true},
	{"armytrailer2", true},
    {"baletrailer", true},
	{"boattrailer", true},
	{"cablecar", true},
    {"docktrailer", true},
	{"freighttrailer", true},
	{"graintrailer", true},
    {"proptrailer", true},
	{"raketrailer", true},
	{"tr2", true},
	{"tr3", true},
    {"tr4", true},
	{"trflat", true},
	{"tvtrailer", true},
	{"tanker", true},
    {"tanker2", true},
	{"trailerlarge", true},
	{"trailerlogs", true},
    {"trailersmall", true},
	{"trailers", true},
	{"trailers2", true},
    {"trailers3", true},
	{"trailers4", true},
	{"freight", true},
    {"freightcar", true},
	{"freightcont1", true},
	{"freightcont2", true},
    {"freightgrain", true},
	{"metrotrain", true},
	{"tankercar", true},
    {"airtug", false},
	{"caddy", false},
	{"caddy2", false},
	{"caddy3", false},
    {"docktug", false},
	{"forklift", false},
	{"mower", false},
    {"ripley", false},
	{"sadler", false},
	{"sadler2", false},
	{"scrap", false},
    {"towtruck", true},
	{"towtruck2", true},
	{"tractor", false},
    {"tractor2", false},
	{"tractor3", false},
	{"utillitruck", false},
    {"utillitruck2", false},
	{"utillitruck3", false},
	{"bison", false},
    {"bison2", false},
	{"bison3", false},
	{"bobcatxl", false},
    {"boxville", false},
	{"boxville2", false},
	{"boxville3", false},
    {"boxville4", false},
	{"boxville5", false},
	{"burrito", false},
    {"burrito2", false},
	{"burrito3", false},
	{"burrito4", false},
    {"burrito5", false},
	{"camper", false},
	{"gburrito", false},
    {"gburrito2", false},
	{"journey", false},
	{"minivan", false},
    {"minivan2", false},
	{"paradise", false},
	{"pony", false},
	{"pony2", false},
    {"rumpo", false},
	{"rumpo2", true},
	{"bate", true},
	{"rumpo3", false},
    {"speedo", false},
	{"speedo2", false},
	{"speedo4", false},
    {"surfer", false},
	{"surfer2", false},
	{"taco", false},
	{"youga", false},
    {"youga2", false},
	{"asbo", false},
	{"kanjo", false},
	{"minitank", false},
    {"yosemite2", false},
	{"caracara2", false},
	{"everon", false},
    {"rebla", false},
	{"komoda", false},
	{"imorgon", false},
	{"vstr", false},
    {"club", false},
	{"dukes3", false},
	{"gauntlet5", false},
    {"yosemite3", false},
	{"openwheel1", false},
	{"openwheel2", false},
    {"landstalker2", false},
	{"seminole2", false},
	{"glendale2", false},
    {"coquette4", false},
	{"penumbra2", false},
	{"manana2", false},
    {"peyote3", false},
	{"tigon", false},
	{"youga3", false},
	{"stryder", false},
    {"gauntlet3", false},
	{"gauntlet4", false},
	{"peyote2", false},
    {"hellion", false},
	{"outlaw", false},
	{"vagrant", false},
	{"zhaba", false},
    {"formula", false},
	{"formula2", false},
	{"novak", false},
    {"drafter", false},
	{"issi7", false},
	{"jugular", false},
	{"locust", false},
    {"neo", false},
	{"paragon", false},
	{"paragon2", false},
	{"sugoi", false},
    {"sultan2", false},
	{"dynasty", false},
	{"jb7002", false},
    {"nebula", false},
	{"retinue2", false},
	{"zion3", false},
	{"emerus", false},
    {"furia", false},
	{"krieger", false},
	{"s80", false},
	{"thrax", false},
    {"zorrusso", false},
	{"avisa", false},
	{"dinghy5", false},
    {"kosatka", false},
	{"longfin", false},
	{"patrolboat", false},
    {"brioso2", false},
	{"weevil", false},
	{"annihilator2", false},
    {"seasparrow2", false},
	{"seasparrow3", false},
	{"vetir", false},
    {"manchez2", false},
	{"verus", false},
	{"winky", false},
    {"alkonost", false},
	{"squaddie", false},
	{"italirsx", false},
    {"veto", true},
	{"veto2", true},
	{"toreador", false},
	{"slamtruck", false},
    {"dominator7", false},
	{"tailgater2", false},
	{"zr350", false},
    {"calico", false},
	{"futo2", false},
	{"euros", false},
	{"jester4", false},
    {"remus", false},
	{"comet6", false},
	{"growler", false},
	{"vectre", false},
    {"cypher", false},
	{"sultan3", false},
	{"rt3000", false},
    {"previon", false},
	{"tahoe", true},
	{"sanchez3", true},
	{"polmesa", true},
    {"nspeedo", true},
	{"audia3", true},
	{"audirs62", true},
    {"audirs6avant", true},
	{"audirs5", true},
	{"audiq8", true},
    {"ducati1200", true},
	{"nc7", true},
	{"audia6", true},
	{"fordraptor", true},
    {"audirs6", false},
	{"bmwi8", false},
	{"bmwm4gts", false},
    {"civictyper", false},
	{"dodgechargersrt", false},
	{"ferrari812", false},
    {"ferrarif12", false},
	{"ferrariitalia", false},
    {"dodgecharger1970", false},
	{"fordmustang", false},
    {"lamborghinihuracan", false},
	{"lancerevolutionx", false},
    {"lancerevolution9", false},
	{"mazdarx7", false},
	{"mazdarx72", false},
    {"mclarenp1", false},
	{"mclarensenna", false},
	{"mercedesgt63", false},
    {"mustangfast", false},
	{"nissangtr", false},
	{"nissangtr2", false},
    {"nissangtr3", false},
	{"nissangtr4", false},
	{"nissangtrnismo", false},
    {"skyliner34", false},
	{"skyliner342", false},
	{"subaruimpreza", false},
    {"subarubrz", false},
	{"toyotasupra", false},
	{"toyotasupra2", false},
    {"acuransx", false},
	{"golfgti", false},
	{"escaladegt900", false},
    {"escalade2021", false},
	{"bmwm5e34", false},
	{"golfmk7", false},
    {"jeepcherokee", false},
	{"porsche911", false},
	{"350z", false},
    {"350logitech", true},
	{"urbandevil", false},
	{"bloodline", false},
    {"shelbygt500", false},
	{"bmwm1wb", false},
	{"lamborghinihuracanlw", false},
    {"panameramansory", false},
	{"wheelchair", true},
	{"ferrarif40", false},
    {"astonmartindbs", false},
	{"nissangtr50", false},
    {"dodgechargerrt69", false},
	{"mercedesamg63", false},
	{"r1", false},
    {"r6", false},
	{"s1000rr", false},
	{"audia4", true},
	{"audia8", true},
    {"audirs7", true},
	{"r1250", false},
	{"r1200", false},
	{"B412", true},
    {"outlaw2", true},
	{"audir82", true},
	{"audir8", false},
    {"aventador750", false},
	{"bmwg20", false},
	{"bmwm8", false},
    {"camaro", false},
	{"dodgeramtrx", false},
	{"dunes3", false},
    {"f8t", false},
	{"fordbronco", false},
	{"golf75r", false},
    {"m1000rr", false},
	{"mclaren570s", false},
	{"porsche718", false},
    {"rs52018", false},
	{"silverado1500", false},
	{"subaruwrx", false},
    {"urus", false},
	{"velar", false},
	{"gol", false},
	{"silvia", false},
    {"audir8v10", false},
	{"ambulancia", false},
	{"skyliner33", false},
    {"fordranger", false},
	{"mercedesgt632", false},
	{"350tj", false},
    {"nissangtrth", false},
	{"riata2", false},
	{"CESTA", false},
    {"fordmustanggt2", false},
	{"porsche911s", false},
	{"rx8hachi", false},
    {"cb500x", false},
	{"m3e46", false},
	{"sorvete", false},
	{"r1200gs", false},
    {"WRclassxv2", false},
	{"bcat", false},
	{"e2000", false},
	{"m3e", false},
    {"WRa45", false},
	{"WRr1200", false},
	{"WRtiger900", false},
    {"er34h", false},
	{"WRbmwx7", false},
	{"WRgle", false},
	{"bmheli", false},
    {"wrc7", false},
	{"rmodz06", false},
	{"rmodsvj", false},
    {"rmodsupralb", false},
	{"rmodrs6r", false},
	{"rmodrover", false},
    {"rmodr50", false},
	{"rmodr8v10", false},
	{"rmodr8alpil", false},
    {"rmodm8c", false},
	{"rmodpanamera2", false},
	{"rmodatlantic", false},
    {"rmodcharger", false},
	{"wrsxr", false},
	{"amarokreb", false},
    {"g7cross", false},
	{"golfrebaixado", false},
	{"pcx", false},
    {"trailblazer", false},
	{"porscheag", false},
	{"jeepag", false},
	{"BXDa45", false},
	{"BXDcla", false},
	{"BXDx6", false},
	{"BXDx7", false},
	{"BXDclassx", false},
	{"BXDgle", false},
	{"BXDsxr", false},
	{"BXDr8", false},
	{"BXDgt63", false},
}
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehList(radius)
    local veh = nil
    local ped = PlayerPedId()
    if IsPedInAnyVehicle(ped) then
        veh = GetVehiclePedIsUsing(ped)
    else
        veh = tvRP.nearVehicle(radius)
    end

    if IsEntityAVehicle(veh) then
        local model = GetEntityModel(veh)
        return veh, NetworkGetNetworkIdFromEntity(veh),
		GetVehicleNumberPlateText(veh), vehicleListHash(model)[1],
		GetVehicleDoorsLockedForPlayer(veh, PlayerId()),
		vehicleListHash(model)[2], GetEntityHealth(veh),
		GetVehicleClass(veh), GetVehicleBodyHealth(veh),
		GetVehicleEngineHealth(veh)
    end
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHAROUND
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehAround()
    local ped = PlayerPedId()
    local veh = tvRP.nearVehicle(4)

    if IsEntityAVehicle(veh) then
        local playerAround = {}
        for _, player in ipairs(GetActivePlayers()) do
            playerAround[#playerAround + 1] = GetPlayerServerId(player)
        end

        return veh, NetworkGetNetworkIdFromEntity(veh), playerAround
    end
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHSITTING
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehSitting()
    local ped = PlayerPedId()
    if IsPedInAnyVehicle(ped) then
        local veh = GetVehiclePedIsUsing(ped)
        local model = GetEntityModel(veh)

        return veh, NetworkGetNetworkIdFromEntity(veh),
        GetVehicleNumberPlateText(veh), vehicleListHash(model)[1]
    end
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHICLEPLATE
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehiclePlate()
    local ped = PlayerPedId()
    if IsPedInAnyVehicle(ped) then
        local veh = GetVehiclePedIsUsing(ped)

        return GetVehicleNumberPlateText(veh)
    end
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHICLENAME
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehicleName()
    local ped = PlayerPedId()
    if IsPedInAnyVehicle(ped) then
        local veh = GetVehiclePedIsUsing(ped)
        return vehicleListHash(GetEntityModel(veh))[1]
    end
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHICLELISTHASH
-----------------------------------------------------------------------------------------------------------------------------------------
function vehicleListHash(hash)
    for k, v in pairs(vehList) do
        if GetHashKey(v[1]) == hash then return v end
    end
    return nil
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHICLEMODEL
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehicleModel(model) return vehicleListHash(model)[1] end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHICLEBLOCK
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehicleBlock(model) return vehicleListHash(model)[2] end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHICLEHASH
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehicleHash()
    local ped = PlayerPedId()
    if IsPedInAnyVehicle(ped) then
        local veh = GetVehiclePedIsUsing(ped)

        return GetEntityModel(veh)
    end
end